# Generated by Django 3.0.2 on 2020-06-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Project Title', max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
    ]
